### PR TITLE
Implementation of the decomposition method using…

### PR DESCRIPTION
**Pull request by vcristiani**
… gaussian mixture models and tests.

### CODE REVIEW

**Review by antotaverna — APPROVED** [review]
Line 7 of models.py ( """Module models."""). Is the model GCgmm missing?

  I think that I do not understand which is the function of the module.

**Comment by nvillagra** [comment]
> Line 7 of models.py ( """Module models."""). Is the model GCgmm missing?
> 
> I think that I do not understand which is the function of the module.

Same here :raised_hand:

**Review by nvillagra — APPROVED** [review]
Everytnig looks fine

**Review by RafaelPignata622 — APPROVED** [review]

**Comment by RafaelPignata622** [comment]
> Line 7 of models.py ( """Module models."""). Is the model GCgmm missing?
> 
> I think that I do not understand which is the function of the module.

I do not understand the question. The module models.py contains all the decompositions methods, including the new Gaussian Mixture. 

In line 7 says that it is the "Module models" because it is the module of models, I think that the right way is the "Methods module" but anyway for another time.

**Comment by nvillagra** [comment]
> > Line 7 of models.py ( """Module models."""). Is the model GCgmm missing?
> > I think that I do not understand which is the function of the module.
> 
> I do not understand the question. The module models.py contains all the decompositions methods, including the new Gaussian Mixture.
> 
> In line 7 says that it is the "Module models" because it is the module of models, I think that the right way is the "Methods module" but anyway for another time.

My question was if GCgmm() shouldn't be listed in   

__all__ = [
    "GCDecomposeMixin",
    "GCClusterMixin",
    "GCAbadi",
    "GCChop",
    "GCKmeans",
]   ?

**Comment by vcristiani** [comment]
> Line 7 of models.py ( """Module models."""). Is the model GCgmm missing?
> 
> I think that I do not understand which is the function of the module.

Refers to the name of the module. That is to say, this module contains all the models used in the dynamic decomposition. We did not use the word methods because it sounded ambiguous.

**Comment by vcristiani** [comment]
> > > Line 7 of models.py ( """Module models."""). Is the model GCgmm missing?
> > > I think that I do not understand which is the function of the module.
> > 
> > 
> > I do not understand the question. The module models.py contains all the decompositions methods, including the new Gaussian Mixture.
> > In line 7 says that it is the "Module models" because it is the module of models, I think that the right way is the "Methods module" but anyway for another time.
> 
> My question was if GCgmm() shouldn't be listed in
> 
> **all** = [
> "GCDecomposeMixin",
> "GCClusterMixin",
> "GCAbadi",
> "GCChop",
> "GCKmeans",
> ] ?

Yes, it should be. Thank you for noticing.

**Pull request merged**
