### PR TITLE
modification of the aling function to correct the way it works

### PR DESCRIPTION
**Pull request by vcristiani**
Now the function rotates all the particles with only one rotation matrix.

### CODE REVIEW

**Comment by antotaverna** [comment]
I think that the changes are ok. However I don't know why the travis fail.

**Comment by nvillagra** [comment]
Is it necessary to have as inputs the masses of the dark matter and the gas?

**Comment by vcristiani** [comment]
@antotaverna Yes, but I see that now it does not fail more.

**Comment by vcristiani** [comment]
@nvillagra Now that you mention it, there's no need. I modify and upload it.

**Comment by vcristiani** [comment]
@antotaverna @nvillagra 
I added the modifications that @nvillagra suggested.

**Review by antotaverna — APPROVED** [review]

**Comment by vcristiani** [comment]
Modification of the aling function

**Pull request merged**
