### PR TITLE
this solves issues #62

### PR DESCRIPTION
**Pull request by vcristiani**
I implemented the calculation of the specific gravitational potential energy with dask, in the energy method. The function is in the file utils.py.

### CODE REVIEW

**Comment by BrunoSanchez** [comment]
I think that to review this I will end up cloning the branch and figure out how is it running.
I would like to encourage the team to accept this PR only when testing for this great implementation is passing. 

I think that we are doing a great job but we need to put effort into testing, until we reverse the process and truly achieve **TDD**.

**Comment by ornemarioni** [comment]
I have made the test of the potential function implemented with dask. This fixes issue #64

**Review by BrunoSanchez — CHANGES_REQUESTED** [review]
Correct style and tests.
We need a succesful build before merging

**Review by BrunoSanchez — APPROVED** [review]
Good, let's move on

**Review by antotaverna — APPROVED** [review]

**Pull request merged**
