### PR TITLE
Unit validation with uttr

### PR DESCRIPTION
**Pull request by ornemarioni**
I had changed the last unit validation adding `uttr`. Because of that, some tests are failing but I have to fix that. I wanna add more tests for the units.

### CODE REVIEW

**Comment by vcristiani** [comment]
I pulled this branch and everything works fine.

**Comment by ornemarioni** [comment]
I had updated the angular momentum property and some of its tests. The coverage isn't yet enough.
Some warnings appear on utils (get_rot_matrix I think)  when it calculates the angular momentum. Please check that with the changes I made @vcristiani @nvillagra

**Comment by vcristiani** [comment]
I looked at the changes, everything looks good. In test_output_galaxy_properties there are some warnings when the test call get_rot_matrix from utils.

**Comment by vcristiani** [comment]
Coverage still needs to be increased.

**Pull request merged**
