### PR TITLE
Issues#59

### PR DESCRIPTION
**Pull request by RafaelPignata622**
I included the tests and their documentation for the last two methods of the Galaxy class. Fixess issue #59

### CODE REVIEW

**Comment by RafaelPignata622** [comment]
The whole branch has changed because the whole branch was really outdated

**Review by nvillagra — COMMENTED** [review]
Everything looks good

**Review by ornemarioni — APPROVED** [review]
All looks good!

**Comment by RafaelPignata622** [comment]
fixes issue #59

**Pull request merged**
